// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkJHbCWmD8N5NjIMgKM-nV-hjSPyrJgfM',
    appId: '1:983881915898:web:30f55015fad63595341843',
    messagingSenderId: '983881915898',
    projectId: 'first-project-e1c66',
    authDomain: 'first-project-e1c66.firebaseapp.com',
    storageBucket: 'first-project-e1c66.appspot.com',
    measurementId: 'G-Y8ZNR5JRV7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKfHNnO2q9vJ4LsbYqYEb8e7TYgRR4Pgs',
    appId: '1:983881915898:android:b07302e2d9878ca3341843',
    messagingSenderId: '983881915898',
    projectId: 'first-project-e1c66',
    storageBucket: 'first-project-e1c66.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBymfjJ7nkHhrYV6jV35MxueRzfSM9LKuU',
    appId: '1:983881915898:ios:97f520c0ae8f185e341843',
    messagingSenderId: '983881915898',
    projectId: 'first-project-e1c66',
    storageBucket: 'first-project-e1c66.appspot.com',
    iosBundleId: 'com.example.mySecondProject',
  );
}
